---
- hosts: database
  become: true
  tasks:

  - name: Update apt repo and cache on Ubuntu box
    apt:
     update_cache: yes
     force_apt_get: yes
     cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
     upgrade: dist
     force_apt_get: yes

  - name: Install required packages
    apt:
      name:
       - wget
       - python3-psycopg2
       - acl
      state: latest

  - name: Set up Postgres 13 repo
    shell: |
     echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    args:
     warn: no	

  - name: Install postgresql
    apt:
     name: postgresql-13
     update_cache: yes

  - name: create database directory for git
    command: mkdir database

  - name: Get database from Git
    git:
     repo: git@gitlab.com:ilcdsysad.upd/rms-2023.git
     version: database
     dest: /home/ilcadmin/database
     accept_hostkey: yes
     update: yes
     force: yes


